language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href /devfest-19/
  - mv dist/devfest-19/index.html dist/devfest-19/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/devfest-19
  on:
    branch: master
