version: 2
jobs:
  build:

    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - run: npm i angular-cli-ghpages --save-dev
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run: yarn ng build --prod --base-href "https://GDG-GANDHINAGAR.github.io/devfest-19/"
      - run: git config --global user.email "parthjansari@outlook.com"
      - run: git config --global user.name "parth181195"
      - run: npx ngh angular-cli-ghpages --dir=/dist/devfest-site --no-silent

