steps:
  - checkout

  # Download and cache dependencies
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

  - run: sudo npm install -g @angular/cli@latest
  - run: sudo npm install -g ngh
  - run: npm install

  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

  - run:
      name: Generate Build
      command: ng build --prod --base-href "https://GDG-GANDHINAGAR.github.io/devfest-19/"

  - run:
      command: |
        ngh --token $TOKEN
