version: 2
jobs:
  build:
    environment:
      GITHUB_NAME: parth181195
      GITHUB_EMAIL: parthjansari@outlook.com
      NAME: devfest-19
    docker:
      - image: circleci/node:10
    steps:
      - checkout
    - restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
    - run: npm i --silent
    - run: npm i -g  @angular/cli
    - run: npm i angular-cli-ghpages --save-dev
    - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
    - run: ng build --prod --base-href "https://GDG-GANDHINAGAR.github.io/devfest-19/
    - run: npx angular-cli-ghpages --dir=dist/devfest-19
